### ISSUE TITLE
file_parser_r을 통한 df 형태소 추출 중 오류

### ISSUE THREAD

**Issue by harryyang1982** [NamyounKim/NLP4kec#1]
안녕하세요. NLP4kec 패키지 배우려는 연구자입니다.

나성호님(https://github.com/MrKevinNa/TextMining/blob/master/Step3%20Create%20xlsx%20file%20and%20Parsing.R ) github을 참조하여 작업하던 도중, 기존의 text_parser 대신 file_parser_r 명령어로 xlsx 파일을 추출하려 했는데 에러 메시지가 나옵니다. 혹시 도움이 가능하시다면, 해결을 부탁 드려도 될런지요.

`parsed <- file_parser_r(tmdf1, language = "ko")`
# Error in .jcall(obj, "[Ljava/lang/String;", "rTextParserToR", as.character(path),  : 
  method rTextParserToR with signature ([Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String; not found

![2018-02-14 8 22 31](https://user-images.githubusercontent.com/14248432/36201877-e175d158-11c4-11e8-950b-3a184efda709.png)

**Comment by NamyounKim** [comment]
안녕하세요.

보내주신 캡쳐화면에서 tmdf1이라는 데이터 프레임을 input으로 넣는데

이럴때는 아래와 같이 형태소분석 대상이 되는 컬럼명을 지정해서 vector형태로 input을 넣어야 합니다.

r_parser_r(tmdf1$content, language = "ko")


참고 사항으로

   - file_parser_r을 사용할때는 파일 패스명을 넣어주셔야 합니다.
   - NLP4kec 버전이 1.1.0인지 확인하고 사용해주세요.

감사합니다.

2018-02-14 20:23 GMT+09:00 Harry Yang <notifications@github.com>:

**Comment by harryyang1982** [comment]
잘 해결이 되었습니다. 고맙습니다!!
